config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  resources :spaces do
    resources :bookings, only: [:create, :show]
  end
  resources :bookings, only: [:destroy]

  get '/dashboards/host', to: "dashboards#host", as: 'host_dashboard'
  get '/dashboards/user', to: "dashboards#user", as: 'user_dashboard'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :space
  belongs_to :user
  validate :start_date_cannot_be_taken
  validate :end_date_cannot_be_taken
  validate :start_date_cannot_be_in_the_past
  validate :end_date_cannot_be_in_the_past
  validate :start_date_should_be_before_end_date

  private

  def start_date_cannot_be_taken
    space_existing_bookings = space.bookings
    arrival_date_in_form = start_date
    space_existing_bookings.each do |booking|
      if arrival_date_in_form.between?(booking.start_date, booking.end_date)
        errors.add(:start_date, "is not available :( ")
      end
    end
  end

  def end_date_cannot_be_taken
    space_existing_bookings = space.bookings
    departure_date_in_form = end_date
    space_existing_bookings.each do |booking|
      if departure_date_in_form.between?(booking.start_date, booking.end_date)
        errors.add(:end_date, "is not available :( ")
      end
    end
  end

  def start_date_cannot_be_in_the_past
    if start_date < Date.today
      errors.add(:start_date, "can't be in the past!")
    end
  end

  def end_date_cannot_be_in_the_past
    if end_date < Date.today
      errors.add(:end_date, "can't be in the past!")
    end
  end

  def start_date_should_be_before_end_date
    if start_date > end_date
      errors.add(:start_date, "should be before departure date!")
    end
  end
end

app/models/space.rb
class Space < ApplicationRecord
  has_one_attached :photo
  geocoded_by :address
  after_validation :update_coordinates, if: :will_save_change_to_address?
  has_many :bookings, dependent: :restrict_with_error
  belongs_to :owner, class_name: 'User', foreign_key: 'owner_id'

  ZONES = ['Jumeirah 1', 'DIFC', 'Dubai Marina', 'Dubai Knowledge Park', 'Downtown Dubai', 'Business Bay', 'The Palm Jumeirah']
  validates :name, presence: true
  validates :description, presence: true
  validates :capacity, presence: true
  validates :price_per_day, presence: true
  # validates :area, inclusion: { in: Space::ZONES }
  validates :address, presence: true

  private

  def update_coordinates
    result = Geocoder.search(self.address).first&.data

    return if result.nil?

    self.latitude = result['lat']
    self.longitude = result['lon']
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :photo
  has_many :spaces, foreign_key: "owner_id"
  has_many :bookings, through: :spaces

  has_many :reservations, class_name: "Booking"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :photo])
    devise_parameter_sanitizer.permit(:edit, keys: [:first_name, :last_name, :photo])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  # def new
  #   @space = Space.find(params[:space_id])
  #   @booking = Booking.new
  # end

  def create
    # get the space id use wants to book
    @space = Space.find(params[:space_id])
    # create a new instance of booking class
    # thats will take start and end date from the booking form
    @booking = Booking.new(booking_params)
    # assign space_id, user_id and price_per_day to the booking
    @booking.space = @space
    # assign booking user to current_user
    @booking.user = current_user
    # TODO how to make @booking.price_per_day a static?
    @booking.price_per_day = @space.price_per_day
    # raise
    if @booking.save
      flash[:notice] = "Your booking is confirmed!"
      redirect_to space_booking_path(@space, @booking)
    else
      flash[:notice] = "Please correct your date selection"
      render 'spaces/show'
    end
  end

  def show
    @booking = Booking.find(params[:id])
    @space = Space.find(params[:space_id])
    @days = (@booking.end_date.to_date - @booking.start_date.to_date).to_i+1
    @total = (@days * @booking.price_per_day)
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    flash[:notice] = "Your booking has been succesfully deleted!"
    redirect_to user_dashboard_path(@booking)
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController

  def host
    @spaces = current_user.spaces
    @bookings = current_user.bookings
  end

  def user
    @reservations = current_user.reservations
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @spaces = Space.all.order(created_at: :desc).limit(6)
  end
end

app/controllers/spaces_controller.rb
class SpacesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show, :index]
  def index
    if params[:query].present?
      @search_term = params[:query]
      @spaces = Space.near(params[:query], 100)
    else
      @spaces = Space.all
    end

    # 'geocoded' scope filters only spaces with coordinates
    @markers = @spaces.geocoded.map do |space|
      {
        lat: space.latitude,
        long: space.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { space:space })
      }
    end
  end

  def new
    @space = Space.new
  end

  def create
    @space = Space.new(space_params)
    @space.owner_id = current_user.id

    if @space.save
      redirect_to host_dashboard_path
    else
      render :new
    end
  end

  def show
    @space = Space.find(params[:id])
    @booking = Booking.new
    @markers =
    {
      lat: @space.latitude,
      long: @space.longitude,
      infoWindow: render_to_string(partial: "info_window", locals: { space: @space })
    }
  end

  def destroy
    @space = Space.find(params[:id])
    @space.destroy

    flash[:notice] = "Your space has been correclty deleted"
    redirect_to host_dashboard_path
  end

  def edit
    @space = Space.find(params[:id])
  end

  def update
    @space = Space.find(params[:id])

    if @space.update(space_params)
      redirect_to host_dashboard_path
    else
      render :edit
    end
  end

  private

  def space_params
    params.require(:space).permit(:name, :capacity, :address, :area, :price_per_day, :description, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_booking_widget.html.erb
<%= simple_form_for [@space, @booking] do |f| %>
  <%= f.input :start_date %>
  <%= f.input :end_date %>
  <%= f.button :submit, class: 'btn-green' %>
<% end %>

app/views/bookings/show.html.erb
<div class="container  p-3">
  <div class="card-wrapper">
    <div class="space-info">
      <div class="place-title">
        <h3>Your booking details</h3>
      </div>
      <div class="card-trip">
        <% if @space.photo.attached? %>
          <img src="<%= cl_image_path @space.photo.key%>" />
        <% else %>
          <img src="" />
        <% end %>
        <div class="card-trip-infos">
          <div>
            <h2><%= @space.name %></h2>
            <p><%= @space.address %></p>
            <p><%= @booking.start_date.strftime('%B %e, %Y') %></p>
            <p><%= @booking.end_date.strftime('%B %e, %Y') %></p>
            <p> Capacity for <%= @space.capacity %> people</p>
          </div>
          <p class="card-trip-pricing">Your host will be <%= "#{@space.owner.first_name} #{@space.owner.last_name}" %></p>
          <% if @space.owner.photo.attached? %>
          <img src="<%= cl_image_tag @space.owner.photo.key%>" />
          <% else %>
          <%= image_tag 'missing-avatar.png', class: "avatar-large" %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="booking-details-wrapper">
      <div class="card">
        <div class="bg-white p-3">
          <div class="d-flex justify-content-between mt-3">
            <p><strong>Price per day</strong></p>
            <p>AED <%=@space.price_per_day%> </p>
          </div>
          <div class="d-flex justify-content-between mt-3 border-bottom">
            <p><strong>Total amount of days</strong></p>
            <p>  <%=@days%> </p>
          </div>
          <div class="d-flex justify-content-between mt-3">
            <p><strong>Total</strong></p>
            <p>  <%=@total%> </p>
          </div>
        </div>
      </div>
    </div>
</div>

app/views/dashboards/host.html.erb
<div class="container p-3">
  <h2>Host Dashboard</h2>
  <hr>

    <div class="d-flex justify-content-between align-items-centered mb-2">
      <h3>My Spaces</h3>
      <%= link_to "Add New Space", new_space_path, class: 'btn-green' %>
    </div>
    <div class="cards">
      <% @spaces.each do |space| %>
      <div class="card-trip">
        <% if space.photo.attached? %>
          <%= cl_image_tag space.photo.key %>
        <% end %>
            <%= link_to space_path(space), method: :delete,  data: { confirm: 'Are you sure you want to delete this space?' }, class: 'delete_link' do %>
              <i class="far fa-trash-alt"></i>
            <% end %>
            <%= link_to edit_space_path(space), class: 'update_link' do %>
              <i class="fas fa-pen"></i>
            <% end %>
        <div class="card-trip-infos">
          <div>
            <%= link_to space_path(space) do %>
            <h2><%= space.name %></h2>
            <% end %>
            <p><%= space.description %></p>
          </div>
          <h2 class="card-trip-pricing">AED <%= space.price_per_day %></h2>
          <% if space.owner.photo.attached? %>
          <%= cl_image_tag space.owner.photo.key, class: "card-trip-user avatar-bordered" %>
          <% else %>
          <%= image_tag 'missing-avatar.png', class: "card-trip-user avatar-bordered" %>
          <% end %>
        </div>
      </div>
      <% end %>
    </div>

    <div class="d-flex justify-content-between align-items-centered mb-2 mt-3">
      <h3>My Bookings</h3>
    </div>
    <div class="cards">
      <% @bookings.each do |booking| %>
      <div class="card-trip">
        <% if booking.space.photo.attached? %>
          <%= cl_image_tag booking.space.photo.key %>
        <% end %>
        <div class="card-trip-infos">
          <div>
            <h2><%= booking.space.name %></h2>
            <p><%= booking.space.description %></p>
            <p><%= booking.start_date.strftime('%B %e, %Y') %></p>
            <p><%= booking.end_date.strftime('%B %e, %Y') %></p>
          </div>
          <h2 class="card-trip-pricing">AED <%= booking.price_per_day %></h2>
          <img src="https://kitt.lewagon.com/placeholder/users/krokrob" class="card-trip-user avatar-bordered" />
        </div>
      </div>
      <% end %>
    </div>

</div>

app/views/dashboards/user.html.erb
<div class="container p-3">
  <div class="d-flex justify-content-between align-items-centered mb-2 mt-3">
    <h3>My Reservations</h3>
  </div>
  <div class="cards">
    <% @reservations.each do |reservation| %>
    <div class="card-trip">
      <% if reservation.space.photo.attached? %>
        <%= cl_image_tag reservation.space.photo.key %>
      <% end %>

        <%= link_to booking_path(reservation), method: 'delete', class:'delete_link' do %>
          <button type="button" class="btn btn-danger">Cancel</button>
        <% end %>
      <div class="card-trip-infos">
        <div>
          <h2><%= reservation.space.name %></h2>
          <p><%= reservation.space.area %></p>
          <p><%= reservation.start_date.strftime('%B %e, %Y') %></p>
          <p><%= reservation.end_date.strftime('%B %e, %Y') %></p>
        </div>
        <h2 class="card-trip-pricing">AED <%= reservation.price_per_day %></h2>
        <% if reservation.space.owner.photo.attached? %>
          <%= cl_image_tag reservation.space.owner.photo.key, class: "card-trip-user avatar-bordered" %>
          <% else %>
          <%= image_tag 'missing-avatar.png', class: "card-trip-user avatar-bordered" %>
          <% end %>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SpaceFlx | Where's your next event?</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
  <div class="banner" style="background-image: linear-gradient(-225deg, rgba(20,20,20, 0) 0%, rgba(20,20,20, 0.6) 30%, rgba(20,20,20, 0.0) 90%), url('<%= image_path 'Banner 2.jpg' %>');">
    <!-- code a Hero / Banner section -->
    <div class="container">
      <h1> Your next private party starts here </h1>
      <p>Find the perfect space for your event</p>
      <div class="search-bar mb-3">
        <%= render 'shared/search_bar' %>
      </div>
      <%= link_to "Browse Spaces", spaces_path, class: 'btn-green' %>
      <%= link_to "Add a Space", new_space_path, class: "btn-green" %>
    </div>
  </div>

  <!-- code a "How it works" section -->
  <div class="container">
    <div class="d-flex justify-content-between align-items-centered mb-2">
    </div>
    <h2 class= "card-title mt-3 mb-3" >Thousands of unforgetable locations for your events</h2>
    <div class="cards" id="space-grid">
      <% @spaces.each do |space| %>
      <%= link_to space_path(space) do %>
      <div class="card-trip">
        <% if space.photo.attached? %>
        <%= cl_image_tag space.photo.key %>
        <% end %>
        <div class="card-trip-infos">
          <div>
            <h2><%= space.name %></h2>
            <p><%= space.description %></p>
          </div>
          <h2 class="card-trip-pricing">AED <%= space.price_per_day %></h2>
          <% if space.owner.photo.attached? %>
          <%= cl_image_tag space.owner.photo.key, class: "card-trip-user avatar-bordered" %>
          <% else %>
          <%= image_tag 'missing-avatar.png', class: "card-trip-user avatar-bordered" %>
          <% end %>
        </div>
      </div>
      <% end %>
      <% end %>
    </div>
    <div class="d-flex justify-content-center mt-3">
      <%= link_to "Browse All Spaces", spaces_path, class: 'btn-green' %>
    </div>
  </div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer fixed-bottom">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    SpaceFlx is made with <i class="fas fa-heart"></i> at Le Wagon - Dubai by Batch # 477
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top">
  <%= link_to root_path, class: "navbar-brand" do %>
    <!-- TODO add a final logo, temporary placeholder below -->
    SpaceFlx
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "All Spaces", spaces_path, class: "nav-link" %>
        </li>
         <li class="nav-username">
          <span class="nav-link"><%= current_user.first_name %></span>
        <li class="nav-item dropdown">
          <% if current_user.photo.attached? %>
            <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
            <%= image_tag 'missing-avatar.png', class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "My Reservations", user_dashboard_path, class: "dropdown-item" %>
            <%= link_to "Host Dashboard", host_dashboard_path, class: "dropdown-item" %>
            <hr>
            <%= link_to "Edit My Profile", edit_user_registration_path, class: "dropdown-item" %>
            <hr>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "All Spaces", spaces_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign Up", new_user_registration_path, class: "nav-link btn navbar-signup-btn mr-2" %>
        </li>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link btn navbar-login-btn" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_search_bar.html.erb
<%= form_tag spaces_path, method: :get do %>
<div class="form-row">
  <div class="col-8">
    <%= text_field_tag :query,
      params[:query],
      class: 'form-control form-rounded',
      id: 'space_address',
      placeholder: "Location" %>
  </div>
  <div class="col-4">
    <%= submit_tag "Find spaces", class: 'btn find-button rounded-pill' %>
  </div>
</div>
<% end %>

app/views/spaces/_form.html.erb
<%= simple_form_for @space do |f| %>
  <%= f.input :name %>
  <div class="form-row">
    <%= f.input :capacity %>
    <%= f.input :price_per_day %>
  </div>
  <%= f.input :address, id: 'space_address' %>
  <%= f.input :description %>
  <%= f.input :photo, as: :file %>
  <%= f.button :submit, class: 'btn btn-success' %>
<% end %>

app/views/spaces/_info_window.html.erb
<!-- <h2><%= space.name %></h2>
<p><%= space.address %></p>
 -->
       <%= link_to space_path(space) do %>
      <div class="card-trip">
        <% if space.photo.attached? %>
        <%= cl_image_tag space.photo.key %>
        <% end %>
        <div class="card-trip-infos">
          <div>
            <h2><%= space.name %></h2>
            <p><%= space.address %></p>
          </div>
          <h2 class="card-trip-pricing">AED <%= space.price_per_day %></h2>
          <% if space.owner.photo.attached? %>
          <%= cl_image_tag space.owner.photo.key, class: "card-trip-user avatar-bordered" %>
          <% else %>
          <%= image_tag 'missing-avatar.png', class: "card-trip-user avatar-bordered" %>
          <% end %>
        </div>
      </div>
      <% end %>

app/views/spaces/edit.html.erb
<div class="container p-3">
  <h1>Update your space</h1>
  <%= render 'form', space: @space %>
</div>

app/views/spaces/index.html.erb
<!-- <div class="d-flex justify-content-between"> -->
  <div class="row">
    <div class="listings col-12 col-lg-8 col-xl-7">
      <div class="search-bar">
        <%= render 'shared/search_bar' %>
      </div>
      <div class="listing-titles">
        <h5><%= "#{@spaces.size} spaces" %></h5>
        <h1>
          Spaces
          <% if @search_term.present? %>
            <span>Near <%= @search_term.capitalize %></span>
            <% end %>
        </h1>
      </div>
      <div class="listing-list">
        <% @spaces.each do |space| %>
          <%= link_to space_path(space) do %>
            <div class="card-product my-3">
              <% if space.photo.attached? %>
                <%= cl_image_tag space.photo.key %>
              <% end %>
              <div class="card-product-infos">
                <h2><%= space.name %></h2>
                <p class="address"><i class="fas fa-map-marker-alt"></i> <%= space.address %></p>
                <p class="capacity"><i class="fas fa-users"></i> <%= space.capacity %></p>
                <p class="description mb-2"><%= space.description %></p>
                <div class="d-flex justify-content-between mt-3">
                  <%= link_to space_path(space), class: 'card-action-button flex-grow-1' do %>
                  <i class="far fa-calendar-plus"></i> Book this Space
                  <% end %>
                  <span class="card-price">AED <%= space.price_per_day %> /day</span>
                </div>
                <% if space.owner.photo.attached? %>
                  <%= cl_image_tag space.owner.photo.key, class: "card-product-user avatar-bordered" %>
                <% else %>
                  <%= image_tag 'missing-avatar.png', class: "card-product-user avatar-bordered" %>
                <% end %>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
    <div class="map col-lg-4 col-xl-5">
      <div id="map" data-markers="<%= @markers.to_json %>" data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>
</div>
<!-- </div> -->

app/views/spaces/new.html.erb
<div class="container p-3">
  <h1>List a new space</h1>
  <%= render 'form', space: @space %>
</div>

app/views/spaces/show.html.erb
<div class="container pt-4">
  <div class="row">
    <div class="space-info col-8">
      <div class="place">
          <h2><%= @space.name %></h2>
          <p class="address"><i class="fas fa-map-marker-alt"></i> <%= @space.address %></p>
          <p class="capacity"><i class="fas fa-users"></i> <%= @space.capacity %></p>
          <p class="description"><%= @space.description %></p>
        <% if @space.photo.attached? %>
          <img src="<%= cl_image_path @space.photo.key%>" height="400px" />
        <% else %>
          <img src="" />
        <% end %>
        <div class="owner-info">
        <div class="card-host">
          <% if @space.owner.photo.attached? %>
            <img src='<%= cl_image_path @space.owner.photo.key %>' class="avatar-large" />
          <% else %>
            <%= image_tag 'missing-avatar.png', class: "card-product-user avatar-bordered" %>
          <% end %>
          <div class="card-host-content">
            <p><small>Your host will be</small></p>
            <p><%= "#{@space.owner.first_name} #{@space.owner.last_name}" %></p>
          </div>
        </div>
      </div>
        </div>
    </div>
    <div class="space-info col-4">
          <!-- checkout -->
          <div class="bg-white border p-3 sticky-top">
            <div class="d-flex justify-content-between mt-3">
              <%= simple_form_for [@space, @booking] do |f| %>
                <%= f.input :start_date %>
                <%= f.input :end_date %>
                <%= f.button :submit, class: 'btn find-button w-100' %>
              <% end %>
            </div>
            <div class="d-flex justify-content-between mt-3">
              <p><strong>Price (per day)</strong> </p>
              <p>AED <%= @space.price_per_day %></p>
            </div>

            <div class="d-flex justify-content-between mt-3 border-bottom">
              <p><strong>Number of Days</strong> </p>
              <p id="num-days">1</p>
            </div>

            <div class="d-flex justify-content-between mt-3">
              <p><strong>Total</strong></p>
              <p id="total-price"><strong><%= @space.price_per_day %></strong></p>
            </div>

            <!-- <a href="#" class="btn find-button w-100">Confirm Booking</a> -->

          </div>
          <!-- /checkout -->
    </div>

  </div>
</div>


<!--     <div id="map" class="fixed-top position-sticky" style="width: 50%; height: 100vh;" data-markers="<%= @markers.to_json %>" data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"> -->